### PR TITLE
Allow PHP 7.1+ support with Guzzle 5

### PR DESCRIPTION
**Pull request by Progi1984**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | Relative to Prestashop\Prestashop#13761
| License       | Apache License 2.0

### CODE REVIEW

**Comment by PierreRambaud** [comment]
One more review and merge if it's ok!

**Comment by matks** [comment]
Looks good 👍 

Can you also add this (asked by [Antoine for the compliance topic](https://github.com/PrestaShop/PrestaShop/pull/13761#pullrequestreview-250372786))
- change the name of the library in the headers, readme, etc. but keep the original name where needed in the code for retro-compatibility.
- add a paragraph in the main readme.md to explain that the name is kept for the transition for retro-compatibility purpose.

Maybe in another PR 🤔in order to keep topics split

**Comment by matks** [comment]
Merged,
```
- change the name of the library in the headers, readme, etc. but keep the original name where needed in the code for retro-compatibility.
- add a paragraph in the main readme.md to explain that the name is kept for the transition for retro-compatibility purpose.
```
Can be done in another PR

**Comment by matks** [comment]
@ttoine Current source code file header is:
```
<?php
/*
 * This file is part of the CsaGuzzleBundle package
 *
 * (c) Charles Sarrazin <charles@sarraz.in>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code
 */
```

Do we keep it ? Do we keep it and add PrestaShop as a 2nd contributor ? Do we replace it with PrestaShop header ?

**Comment by ttoine** [comment]
please add a 2nd contributor to make it clear who and why you modified it.

**Pull request merged**
